### ISSUE TITLE
how to building? failed when make?

### ISSUE THREAD

**Issue by andyyuan78** [tlgimenes/CUDADClusterer#1]
ubgpu@ubgpu:~/github/CUDADClusterer$ cmake .
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubgpu/github/CUDADClusterer
ubgpu@ubgpu:~/github/CUDADClusterer$ 
ubgpu@ubgpu:~/github/CUDADClusterer$ ll
total 212
drwxrwxr-x   9 ubgpu ubgpu   4096  7月  6 23:09 ./
drwxrwxr-x 283 ubgpu ubgpu  12288  7月  6 23:09 ../
drwxrwxr-x   3 ubgpu ubgpu   4096  7月  6 23:09 clusterer/
-rw-rw-r--   1 ubgpu ubgpu  12173  7月  6 23:09 CMakeCache.txt
drwxrwxr-x   5 ubgpu ubgpu   4096  7月  6 23:09 CMakeFiles/
-rw-rw-r--   1 ubgpu ubgpu   1844  7月  6 23:09 cmake_install.cmake
-rw-rw-r--   1 ubgpu ubgpu    937  7月  6 23:09 CMakeLists.txt
-rw-rw-r--   1 ubgpu ubgpu 103055  7月  6 23:09 Doxyfile
drwxrwxr-x   8 ubgpu ubgpu   4096  7月  6 23:09 .git/
-rw-rw-r--   1 ubgpu ubgpu    361  7月  6 23:09 .gitignore
drwxrwxr-x   3 ubgpu ubgpu   4096  7月  6 23:09 knn/
-rw-rw-r--   1 ubgpu ubgpu  18027  7月  6 23:09 LICENSE
-rw-rw-r--   1 ubgpu ubgpu   6297  7月  6 23:09 main.cpp
-rw-rw-r--   1 ubgpu ubgpu   6887  7月  6 23:09 Makefile
drwxrwxr-x   3 ubgpu ubgpu   4096  7月  6 23:09 parser/
-rw-rw-r--   1 ubgpu ubgpu    726  7月  6 23:09 README.md
drwxrwxr-x   3 ubgpu ubgpu   4096  7月  6 23:09 utils/
drwxrwxr-x   3 ubgpu ubgpu   4096  7月  6 23:09 xdrfile/
ubgpu@ubgpu:~/github/CUDADClusterer$ 

ubgpu@ubgpu:~/github/CUDADClusterer$ make
Scanning dependencies of target knn
Linking CXX static library libknn.a
[  0%] Built target knn
Scanning dependencies of target xdrfile
[ 25%] Building C object xdrfile/CMakeFiles/xdrfile.dir/xdrfile.c.o
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
[ 50%] Building C object xdrfile/CMakeFiles/xdrfile.dir/xdrfile_trr.c.o
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
[ 75%] Building C object xdrfile/CMakeFiles/xdrfile.dir/xdrfile_xtc.c.o
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
Linking C static library libxdrfile.a
[ 75%] Built target xdrfile
Scanning dependencies of target parser
Linking CXX static library libparser.a
[ 75%] Built target parser
Scanning dependencies of target clusterer
Linking CXX static library libclusterer.a
[ 75%] Built target clusterer
Scanning dependencies of target utils
Linking CXX static library libutils.a
[ 75%] Built target utils
Scanning dependencies of target gpu_clusterer
[100%] Building CXX object CMakeFiles/gpu_clusterer.dir/main.cpp.o
In file included from /home/ubgpu/github/CUDADClusterer/main.cpp:13:0:
/home/ubgpu/github/CUDADClusterer/utils/reader_xtc.hpp:28:29: fatal error: xdrfile/xdrfile.h: No such file or directory
 #include "xdrfile/xdrfile.h"
                             ^
compilation terminated.
make[2]: *** [CMakeFiles/gpu_clusterer.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/gpu_clusterer.dir/all] Error 2
make: *** [all] Error 2
ubgpu@ubgpu:~/github/CUDADClusterer$ cmake
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.

ubgpu@ubgpu:~/github/CUDADClusterer$

**Comment by tlgimenes** [comment]
Hello, 

This project is old and is currently discontinued. I'm currently working on a refactoring of this project and I'm currently finishing the GPU implementation that will use a hybrid implementation of MPI/OpenCL instead of CUDA only.

The current CPU implementation using a hybrid of pthreads/MPI is working, but the code will only be published once the OpenCL implementation is over.

Thank you and I'm open for more questions/discussions !

**Comment by andyyuan78** [comment]
ok, wait the good news
